import "oaidl.idl";
import "ocidl.idl";

[
	uuid(c503f532-443a-4c69-8300-ccd1fbdb3839),
	version(2.0),
]
interface DefaultIfName
{

	typedef struct Struct_16_t
	{
		long 	StructMember0;
		short 	StructMember1;
		short 	StructMember2;
		byte 	StructMember3[8];
	}Struct_16_t;

	typedef struct Struct_28_t
	{
		hyper 	StructMember0;
	}Struct_28_t;

	typedef struct Struct_40_t
	{
		long 	StructMember0;
		long 	StructMember1;
		long 	StructMember2[4];
	}Struct_40_t;

	/* FC_HARD_STRUCT processed as a FC_BOGUS_STRUC  */

	typedef struct Struct_58_t
	{
		long 	StructMember0;
		hyper 	StructMember1;
		hyper 	StructMember2;
		hyper 	StructMember3;
		hyper 	StructMember4;
		hyper 	StructMember5[4];
	}Struct_58_t;

	/* FC_HARD_STRUCT processed as a FC_BOGUS_STRUC  */

	typedef struct Struct_78_t
	{
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember0;
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember1;
		struct Struct_16_t 	StructMember2;
		struct Struct_28_t 	StructMember3;
		struct Struct_28_t 	StructMember4;
		struct Struct_40_t 	StructMember5;
		struct Struct_58_t 	StructMember6;
		hyper 	StructMember7;
	}Struct_78_t;

	typedef struct Struct_110_t
	{
		long 	StructMember0;
	}Struct_110_t;

	typedef struct Struct_126_t
	{
		long 	StructMember0;
		long 	StructMember1;
	}Struct_126_t;

	/* FC_HARD_STRUCT processed as a FC_BOGUS_STRUC  */

	typedef struct Struct_144_t
	{
		long 	StructMember0;
		struct Struct_78_t 	StructMember1;
		struct Struct_78_t 	StructMember2;
		struct Struct_40_t 	StructMember3;
		struct Struct_110_t 	StructMember4[4];
		struct Struct_126_t 	StructMember5[11];
		struct Struct_28_t 	StructMember6;
	}Struct_144_t;

	typedef [switch_type(long)] union union_222
	{
		[case(1)] [unique] struct Struct_444_t* unionMember_1;
		[case(3)] [unique] struct Struct_502_t* unionMember_3;
		[case(4)] [unique] struct Struct_530_t* unionMember_4;
		[case(5)] [unique] struct Struct_552_t* unionMember_5;
		[case(2)] [unique] struct Struct_576_t* unionMember_2;
		[case(6)] [unique] struct Struct_594_t* unionMember_6;
		[case(7)] [unique] struct Struct_110_t* unionMember_7;
		[case(8)] [unique] struct Struct_630_t* unionMember_8;
		[case(9)] [unique] struct Struct_674_t* unionMember_9;
		[case(10)] [unique] struct Struct_706_t* unionMember_10;
		[case(12)] [unique] struct Struct_756_t* unionMember_12;
		[case(13)] [unique] struct Struct_126_t* unionMember_13;
		[case(14)] [unique] struct Struct_780_t* unionMember_14;
		[case(15)] [unique] struct Struct_800_t* unionMember_15;
		[case(16)] [unique] struct Struct_110_t* unionMember_16;
		[case(17)] [unique] struct Struct_110_t* unionMember_17;
		[case(18)] [unique] struct Struct_820_t* unionMember_18;
		[case(19)] [unique] struct Struct_840_t* unionMember_19;
		[case(20)] [unique] struct Struct_856_t* unionMember_20;
		[case(21)] [unique] struct Struct_884_t* unionMember_21;
		[case(22)] [unique] struct Struct_954_t* unionMember_22;
		/* no default member to print for this Union.
		An exception will be raised if the switch_is value does not match any of the cases values */
	} union_222;


	typedef [switch_type(long)] union union_368
	{
		[case(0)] [unique] struct Struct_110_t* unionMember_0;
		[case(1)] [unique] struct Struct_110_t* unionMember_1;
		[case(2)] [unique] struct Struct_110_t* unionMember_2;
		[case(3)] [unique] struct Struct_110_t* unionMember_3;
		[case(4)] [unique] struct Struct_110_t* unionMember_4;
		[case(5)] [unique] struct Struct_110_t* unionMember_5;
		[case(6)] [unique] struct Struct_110_t* unionMember_6;
		[case(7)] [unique] struct Struct_110_t* unionMember_7;
		[case(8)] [unique] struct Struct_110_t* unionMember_8;
		[case(9)] [unique] struct Struct_110_t* unionMember_9;
		[case(10)] [unique] struct Struct_110_t* unionMember_10;
		/* no default member to print for this Union.
		An exception will be raised if the switch_is value does not match any of the cases values */
	} union_368;


	typedef struct Struct_444_t
	{
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember0;
		long 	StructMember1;
		[switch_is(StructMember0)] union union_368 	StructMember2;
	}Struct_444_t;

	typedef struct Struct_476_t
	{
		[unique] [string] wchar_t* StructMember0;
		[unique] [string] wchar_t* StructMember1;
		long 	StructMember2;
		long 	StructMember3;
		[unique] [size_is(StructMember3)] char* StructMember4;
	}Struct_476_t;

	typedef struct Struct_502_t
	{
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember0;
		[unique] struct Struct_476_t* StructMember1;
		struct Struct_58_t 	StructMember2;
		struct Struct_40_t 	StructMember3;
	}Struct_502_t;

	typedef struct Struct_530_t
	{
		hyper 	StructMember0;
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember1;
		long 	StructMember2;
		[unique] struct Struct_476_t* StructMember3;
	}Struct_530_t;

	typedef struct Struct_552_t
	{
		[unique] struct Struct_476_t* StructMember0;
		[unique] struct Struct_476_t* StructMember1;
	}Struct_552_t;

	typedef struct Struct_576_t
	{
		hyper 	StructMember0;
		long 	StructMember1;
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember2;
		long 	StructMember3;
	}Struct_576_t;

	typedef struct Struct_594_t
	{
		long 	StructMember0;
		long 	StructMember1;
		long 	StructMember2;
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember3;
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember4;
		[unique] [string] wchar_t* StructMember5;
	}Struct_594_t;

	typedef struct Struct_630_t
	{
		long 	StructMember0;
		[unique] [size_is(StructMember0)] char* StructMember1;
	}Struct_630_t;

	typedef struct Struct_674_t
	{
		[unique] [string] wchar_t* StructMember0;
		long 	StructMember1;
		long 	StructMember2;
		[unique] [size_is(StructMember2)] char* StructMember3;
		long 	StructMember4;
		[unique] [size_is(StructMember4)] char* StructMember5;
	}Struct_674_t;

	typedef struct Struct_706_t
	{
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember0;
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember1;
		[unique] [string] wchar_t* StructMember2;
		struct Struct_28_t 	StructMember3;
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember4;
		[unique] [string] wchar_t* StructMember5;
		[unique] [string] wchar_t* StructMember6;
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember7;
	}Struct_706_t;

	typedef struct Struct_756_t
	{
		long 	StructMember0;
		long 	StructMember1;
		[unique] [size_is(StructMember1)] char* StructMember2;
	}Struct_756_t;

	typedef struct Struct_780_t
	{
		struct Struct_126_t 	StructMember0;
		struct Struct_126_t 	StructMember1;
		long 	StructMember2;
		long 	StructMember3;
	}Struct_780_t;

	typedef struct Struct_800_t
	{
		long 	StructMember0;
		[unique] [string] wchar_t* StructMember1;
	}Struct_800_t;

	typedef struct Struct_820_t
	{
		[unique] [string] wchar_t* StructMember0;
		long 	StructMember1;
	}Struct_820_t;

	/* FC_HARD_STRUCT processed as a FC_BOGUS_STRUC  */

	typedef struct Struct_840_t
	{
		long 	StructMember0;
		hyper 	StructMember1;
	}Struct_840_t;

	typedef struct Struct_856_t
	{
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember0;
		[unique] [string] wchar_t* StructMember1;
		[unique] [string] wchar_t* StructMember2;
		long 	StructMember3;
	}Struct_856_t;

	typedef struct Struct_884_t
	{
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember0;
		[unique] [string] wchar_t* StructMember1;
		[unique] [string] wchar_t* StructMember2;
		[unique] [string] wchar_t* StructMember3;
		long 	StructMember4;
	}Struct_884_t;

	typedef struct Struct_916_t
	{
		long 	StructMember0;
		long 	StructMember1;
		[unique] [size_is(StructMember1)] char* StructMember2;
	}Struct_916_t;

	typedef struct Struct_954_t
	{
		long 	StructMember0;
		[unique] /* [DBG] FC_BOGUS_ARRAY */ [size_is(StructMember0)] /*  */ struct Struct_916_t* StructMember1;
	}Struct_954_t;

	typedef struct Struct_970_t
	{
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember0;
		long 	StructMember1;
		struct Struct_28_t 	StructMember2;
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember3;
		[switch_is(StructMember3)] union union_222 	StructMember4;
	}Struct_970_t;

	typedef [switch_type(long)] union union_1078
	{
		[case(0)] [unique] struct Struct_110_t* unionMember_0;
		[case(1)] [unique] struct Struct_1118_t* unionMember_1;
		[case(2)] [unique] struct Struct_110_t* unionMember_2;
		[case(3)] [unique] struct Struct_110_t* unionMember_3;
		[case(4)] [unique] struct Struct_1156_t* unionMember_4;
		/* no default member to print for this Union.
		An exception will be raised if the switch_is value does not match any of the cases values */
	} union_1078;


	typedef struct Struct_1118_t
	{
		struct Struct_28_t 	StructMember0;
		hyper 	StructMember1;
		hyper 	StructMember2;
		hyper 	StructMember3;
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember4;
		long 	StructMember5;
		[unique] [string] wchar_t* StructMember6;
		[unique] [string] wchar_t* StructMember7;
		[unique] [string] wchar_t* StructMember8;
	}Struct_1118_t;

	typedef struct Struct_1156_t
	{
		[unique] [string] wchar_t* StructMember0;
		[unique] [string] wchar_t* StructMember1;
		long 	StructMember2;
		long 	StructMember3;
		[unique] [string] wchar_t* StructMember4;
		[unique] [string] wchar_t* StructMember5;
	}Struct_1156_t;

	typedef struct Struct_1232_t
	{
		hyper 	StructMember0;
		struct Struct_16_t 	StructMember1;
		[unique] [string] wchar_t* StructMember2;
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember3;
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember4;
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember5;
		long 	StructMember6;
		long 	StructMember7;
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember8;
		long 	StructMember9;
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember10[6];
		long 	StructMember11;
		[unique] /* [DBG] FC_BOGUS_ARRAY */ [size_is(StructMember11)] /*  */ struct Struct_476_t** StructMember12;
		struct Struct_28_t 	StructMember13;
		long 	StructMember14;
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember15;
		struct Struct_16_t 	StructMember16;
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember17;
		[switch_is(StructMember3)] union union_1078 	StructMember18;
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember19;
		[unique] [string] wchar_t* StructMember20;
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember21;
		[unique] [string] wchar_t* StructMember22;
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember23;
		long 	StructMember24;
		struct Struct_28_t 	StructMember25;
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember26;
		struct Struct_28_t 	StructMember27;
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember28;
		long 	StructMember29;
		long 	StructMember30;
		[unique] [string] wchar_t* StructMember31;
		long 	StructMember32;
		[unique] /* [DBG] FC_BOGUS_ARRAY */ [size_is(StructMember32)] /*  */ struct Struct_476_t** StructMember33;
		long 	StructMember34;
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember35;
		long 	StructMember36;
		long 	StructMember37;
		long 	StructMember38;
	}Struct_1232_t;

	typedef [switch_type(long)] union union_1370
	{
		[case(1)] [unique] struct Struct_1232_t* unionMember_1;
		/* no default member to print for this Union.
		An exception will be raised if the switch_is value does not match any of the cases values */
	} union_1370;


	typedef struct Struct_1382_t
	{
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember0;
		[switch_is(StructMember0)] union union_1370 	StructMember1;
	}Struct_1382_t;

	typedef struct Struct_1434_t
	{
		long 	StructMember0;
		[unique] [size_is(StructMember0)] hyper* StructMember1;
		[unique] [size_is(StructMember0)] /* enum_32 : typedef [v1_enum] enum  */ long* StructMember2;
	}Struct_1434_t;

	typedef struct Struct_1516_t
	{
		hyper 	StructMember0;
		struct Struct_28_t 	StructMember1;
	}Struct_1516_t;

	typedef struct Struct_1536_t
	{
		struct Struct_1516_t 	StructMember0;
		struct Struct_1516_t 	StructMember1;
		struct Struct_1516_t 	StructMember2;
		struct Struct_1516_t 	StructMember3;
		struct Struct_1516_t 	StructMember4;
		struct Struct_1516_t 	StructMember5;
		struct Struct_1516_t 	StructMember6;
		struct Struct_1516_t 	StructMember7;
		struct Struct_1516_t 	StructMember8[4];
	}Struct_1536_t;

	typedef struct Struct_1682_t
	{
		long 	StructMember0;
		hyper 	StructMember1;
		[unique] [string] wchar_t* StructMember2;
		long 	StructMember3;
		[unique] [string] wchar_t* StructMember4;
		[unique] [string] wchar_t* StructMember5;
		long 	StructMember6;
		[unique] [string] wchar_t* StructMember7;
	}Struct_1682_t;

	typedef struct Struct_1740_t
	{
		long 	StructMember0;
		[unique] /* [DBG] FC_BOGUS_ARRAY */ [size_is(StructMember0)] /*  */ struct Struct_1682_t** StructMember1;
	}Struct_1740_t;

	typedef struct Struct_1872_t
	{
		long 	StructMember0;
		long 	StructMember1;
		[unique] [string] wchar_t* StructMember2;
	}Struct_1872_t;

	typedef struct Struct_1920_t
	{
		struct Struct_16_t 	StructMember0;
		long 	StructMember1;
		long 	StructMember2;
		long 	StructMember3;
		long 	StructMember4;
		long 	StructMember5;
		long 	StructMember6;
		long 	StructMember7;
		long 	StructMember8;
		long 	StructMember9;
		long 	StructMember10;
		long 	StructMember11;
		long 	StructMember12;
		long 	StructMember13;
		long 	StructMember14;
		long 	StructMember15;
		long 	StructMember16;
		long 	StructMember17;
		long 	StructMember18;
		long 	StructMember19;
		long 	StructMember20;
	}Struct_1920_t;

	typedef struct Struct_1978_t
	{
		long 	StructMember0;
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember1;
	}Struct_1978_t;

	typedef struct Struct_2070_t
	{
		[unique] [string] wchar_t* StructMember0;
	}Struct_2070_t;

	typedef [switch_type(long)] union union_2142
	{
		[case(0)] [unique] struct Struct_2194_t* unionMember_0;
		[case(1)] [unique] struct Struct_2208_t* unionMember_1;
		[case(2)] [unique] struct Struct_2270_t* unionMember_2;
		[case(3)] [unique] struct Struct_2300_t* unionMember_3;
		[case(4)] [unique] struct Struct_2314_t* unionMember_4;
		[case(5)] [unique] struct Struct_2356_t* unionMember_5;
		[case(6)] [unique] struct Struct_2408_t* unionMember_6;
		/* no default member to print for this Union.
		An exception will be raised if the switch_is value does not match any of the cases values */
	} union_2142;


	typedef struct Struct_2194_t
	{
		struct Struct_28_t 	StructMember0;
		hyper 	StructMember1;
	}Struct_2194_t;

	typedef struct Struct_2208_t
	{
		struct Struct_28_t 	StructMember0;
		hyper 	StructMember1;
		[unique] [string] wchar_t* StructMember2;
		[unique] [string] wchar_t* StructMember3;
		[unique] [string] wchar_t* StructMember4;
		hyper 	StructMember5;
		long 	StructMember6;
		struct Struct_16_t 	StructMember7;
		hyper 	StructMember8;
		[unique] [string] wchar_t* StructMember9;
		struct Struct_28_t 	StructMember10;
		hyper 	StructMember11;
		struct Struct_28_t 	StructMember12;
		hyper 	StructMember13;
		hyper 	StructMember14;
		hyper 	StructMember15;
		hyper 	StructMember16;
		hyper 	StructMember17;
		hyper 	StructMember18;
	}Struct_2208_t;

	typedef struct Struct_2270_t
	{
		struct Struct_28_t 	StructMember0;
		hyper 	StructMember1;
		[unique] [string] wchar_t* StructMember2;
		[unique] [string] wchar_t* StructMember3;
		hyper 	StructMember4;
	}Struct_2270_t;

	typedef struct Struct_2300_t
	{
		struct Struct_28_t 	StructMember0;
	}Struct_2300_t;

	typedef struct Struct_2314_t
	{
		long 	StructMember0;
		struct Struct_28_t 	StructMember1;
		hyper 	StructMember2;
		[unique] [string] wchar_t* StructMember3;
		[unique] [string] wchar_t* StructMember4;
		hyper 	StructMember5;
		struct Struct_28_t 	StructMember6;
		hyper 	StructMember7;
		struct Struct_28_t 	StructMember8;
		hyper 	StructMember9;
	}Struct_2314_t;

	typedef struct Struct_2356_t
	{
		long 	StructMember0;
		struct Struct_28_t 	StructMember1;
		hyper 	StructMember2;
		[unique] [string] wchar_t* StructMember3;
		[unique] [string] wchar_t* StructMember4;
	}Struct_2356_t;

	typedef struct Struct_2408_t
	{
		long 	StructMember0;
		struct Struct_28_t 	StructMember1;
		hyper 	StructMember2;
		[unique] [string] wchar_t* StructMember3;
		[unique] [string] wchar_t* StructMember4;
		long 	StructMember5;
		[unique] /* [DBG] FC_BOGUS_ARRAY */ [size_is(StructMember5)] /*  */ struct Struct_916_t* StructMember6;
	}Struct_2408_t;

	typedef struct Struct_2442_t
	{
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember0;
		[switch_is(StructMember0)] union union_2142 	StructMember1;
	}Struct_2442_t;

	typedef struct Struct_2482_t
	{
		struct Struct_110_t 	StructMember0;
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember1;
		[unique] [string] wchar_t* StructMember2;
		long 	StructMember3;
		[unique] [size_is(StructMember3)] wchar_t* StructMember4;
		long 	StructMember5;
		[unique] [size_is(StructMember5)] wchar_t* StructMember6;
	}Struct_2482_t;

	typedef struct Struct_2516_t
	{
		struct Struct_2442_t 	StructMember0;
		struct Struct_2482_t 	StructMember1;
		hyper 	StructMember2;
	}Struct_2516_t;

	typedef struct Struct_2558_t
	{
		struct Struct_16_t 	StructMember0;
		long 	StructMember1;
		long 	StructMember2;
		hyper 	StructMember3;
	}Struct_2558_t;

	typedef struct Struct_2640_t
	{
		hyper 	StructMember0;
		[unique] [string] wchar_t* StructMember1;
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember2;
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember3;
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember4;
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember5;
		long 	StructMember6;
		[unique] /* [DBG] FC_BOGUS_ARRAY */ [size_is(StructMember6)] /*  */ struct Struct_476_t** StructMember7;
		long 	StructMember8;
		long 	StructMember9;
	}Struct_2640_t;

	typedef struct Struct_2672_t
	{
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember0;
		long 	StructMember1;
		hyper 	StructMember2;
	}Struct_2672_t;

	/* FC_HARD_STRUCT processed as a FC_BOGUS_STRUC  */

	typedef struct Struct_2680_t
	{
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember0;
		struct Struct_2672_t 	StructMember1;
	}Struct_2680_t;

	typedef struct Struct_2798_t
	{
		[unique] [string] wchar_t* StructMember0;
		hyper 	StructMember1;
		long 	StructMember2;
		[unique] [string] wchar_t* StructMember3;
		[unique] [string] wchar_t* StructMember4;
		[unique] [string] wchar_t* StructMember5;
	}Struct_2798_t;

	typedef struct Struct_2854_t
	{
		[unique] [string] wchar_t* StructMember0;
		long 	StructMember1;
		[unique] [string] wchar_t* StructMember2;
		long 	StructMember3;
		[unique] [string] wchar_t* StructMember4;
		[unique] [string] wchar_t* StructMember5;
		[unique] [string] wchar_t* StructMember6;
	}Struct_2854_t;

	typedef struct Struct_2900_t
	{
		[unique] [string] wchar_t* StructMember0;
		[unique] [string] wchar_t* StructMember1;
		long 	StructMember2;
	}Struct_2900_t;

	typedef struct Struct_2986_t
	{
		[unique] [string] wchar_t* StructMember0;
		[unique] [string] wchar_t* StructMember1;
	}Struct_2986_t;

	typedef struct Struct_3040_t
	{
		long 	StructMember0;
		[unique] /* [DBG] FC_BOGUS_ARRAY */ [size_is(StructMember0)] /*  */ struct Struct_2986_t** StructMember1;
		long 	StructMember2;
		[unique] [size_is(StructMember2)] char* StructMember3;
		hyper 	StructMember4;
		long 	StructMember5;
	}Struct_3040_t;

	typedef struct Struct_3108_t
	{
		struct Struct_16_t 	StructMember0;
		[unique] [string] wchar_t* StructMember1;
		[unique] [string] wchar_t* StructMember2;
	}Struct_3108_t;

	typedef struct Struct_3166_t
	{
		[unique] [string] wchar_t* StructMember0;
		long 	StructMember1;
		hyper 	StructMember2;
	}Struct_3166_t;

	typedef struct Struct_3220_t
	{
		struct Struct_3166_t 	StructMember0;
		[unique] [string] wchar_t* StructMember1;
		struct Struct_16_t 	StructMember2;
		long 	StructMember3;
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember4;
		long 	StructMember5;
		char 	StructMember6[32];
	}Struct_3220_t;

	typedef struct Struct_3280_t
	{
		[unique] [string] wchar_t* StructMember0;
	}Struct_3280_t;

	typedef struct Struct_3302_t
	{
		long 	StructMember0;
		[unique] struct Struct_3220_t* StructMember1;
		[unique] struct Struct_3108_t* StructMember2;
	}Struct_3302_t;

	typedef struct Struct_3350_t
	{
		long 	StructMember0;
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember1;
		long 	StructMember2;
	}Struct_3350_t;

	typedef struct Struct_3370_t
	{
		long 	StructMember0;
		[unique] [string] wchar_t* StructMember1;
		[unique] [string] wchar_t* StructMember2;
		[unique] [string] wchar_t* StructMember3;
		[unique] [string] wchar_t* StructMember4;
		[unique] [string] wchar_t* StructMember5;
		[unique] [string] wchar_t* StructMember6;
		[unique] [string] wchar_t* StructMember7;
		[unique] [string] wchar_t* StructMember8;
		[unique] [string] wchar_t* StructMember9;
		hyper 	StructMember10;
		long 	StructMember11;
		hyper 	StructMember12;
		long 	StructMember13;
		long 	StructMember14;
		[unique] [string] wchar_t* StructMember15;
		[unique] [string] wchar_t* StructMember16;
		short 	StructMember17;
		short 	StructMember18;
		[unique] [string] wchar_t* StructMember19;
		long 	StructMember20;
		long 	StructMember21;
	}Struct_3370_t;

	typedef [switch_type(long)] union union_3514
	{
		[case(0)] [unique] struct Struct_3552_t* unionMember_0;
		/* no default member to print for this Union.
		An exception will be raised if the switch_is value does not match any of the cases values */
	} union_3514;


	typedef struct Struct_3552_t
	{
		hyper 	StructMember0;
		long 	StructMember1;
		[unique] /* [DBG] FC_BOGUS_ARRAY */ [size_is(StructMember1)] /*  */ struct Struct_476_t** StructMember2;
	}Struct_3552_t;

	typedef struct Struct_3570_t
	{
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember0;
		[switch_is(StructMember0)] union union_3514 	StructMember1;
	}Struct_3570_t;

	typedef [switch_type(long)] union union_3624
	{
		[case(1)] [unique] struct Struct_3640_t* unionMember_1;
		/* no default member to print for this Union.
		An exception will be raised if the switch_is value does not match any of the cases values */
	} union_3624;


	typedef struct Struct_3640_t
	{
		hyper 	StructMember0;
		long 	StructMember1;
		long 	StructMember2;
		long 	StructMember3;
	}Struct_3640_t;

	typedef struct Struct_3654_t
	{
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember0;
		[switch_is(StructMember0)] union union_3624 	StructMember1;
	}Struct_3654_t;

	typedef [switch_type(long)] union union_3714
	{
		[case(1)] [unique] struct Struct_3742_t* unionMember_1;
		[case(2)] [unique] struct Struct_3762_t* unionMember_2;
		[case(3)] [unique] struct Struct_3782_t* unionMember_3;
		/* no default member to print for this Union.
		An exception will be raised if the switch_is value does not match any of the cases values */
	} union_3714;


	typedef struct Struct_3742_t
	{
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember0;
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember1;
		hyper 	StructMember2;
		hyper 	StructMember3;
		long 	StructMember4;
	}Struct_3742_t;

	typedef struct Struct_3762_t
	{
		[unique] struct Struct_3742_t* StructMember0;
		long 	StructMember1;
	}Struct_3762_t;

	typedef struct Struct_3782_t
	{
		[unique] struct Struct_3762_t* StructMember0;
		long 	StructMember1;
		hyper 	StructMember2;
	}Struct_3782_t;

	typedef struct Struct_3800_t
	{
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember0;
		[switch_is(StructMember0)] union union_3714 	StructMember1;
	}Struct_3800_t;

	typedef struct Struct_3824_t
	{
		long 	StructMember0;
		[unique] [string] wchar_t* StructMember1;
		[unique] [string] wchar_t* StructMember2;
	}Struct_3824_t;

	typedef struct Struct_3880_t
	{
		long 	StructMember0;
		[unique] [string] wchar_t* StructMember1;
		[unique] [string] wchar_t* StructMember2;
		[unique] [string] wchar_t* StructMember3;
	}Struct_3880_t;

	typedef [switch_type(long)] union union_3928
	{
		[case(1)] [unique] struct Struct_3944_t* unionMember_1;
		/* no default member to print for this Union.
		An exception will be raised if the switch_is value does not match any of the cases values */
	} union_3928;


	/* FC_HARD_STRUCT processed as a FC_BOGUS_STRUC  */

	typedef struct Struct_3944_t
	{
		long 	StructMember0;
		long 	StructMember1;
		long 	StructMember2;
		hyper 	StructMember3;
	}Struct_3944_t;

	typedef struct Struct_3958_t
	{
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember0;
		[switch_is(StructMember0)] union union_3928 	StructMember1;
	}Struct_3958_t;

	typedef [switch_type(long)] union union_3992
	{
		[case(1)] [unique] struct Struct_4044_t* unionMember_1;
		[case(2)] [unique] struct Struct_4066_t* unionMember_2;
		[case(3)] [unique] struct Struct_4086_t* unionMember_3;
		[case(4)] [unique] struct Struct_4118_t* unionMember_4;
		[case(5)] [unique] struct Struct_4142_t* unionMember_5;
		/* no default member to print for this Union.
		An exception will be raised if the switch_is value does not match any of the cases values */
	} union_3992;


	typedef struct Struct_4044_t
	{
		long 	StructMember0;
		long 	StructMember1;
		long 	StructMember2;
		[unique] [size_is(StructMember2)] char* StructMember3;
	}Struct_4044_t;

	typedef struct Struct_4066_t
	{
		struct Struct_4044_t 	StructMember0;
		long 	StructMember1;
	}Struct_4066_t;

	typedef struct Struct_4086_t
	{
		struct Struct_4066_t 	StructMember0;
		long 	StructMember1;
	}Struct_4086_t;

	typedef struct Struct_4118_t
	{
		struct Struct_4086_t 	StructMember0;
		long 	StructMember1;
		long 	StructMember2;
		[unique] [size_is(StructMember2)] char* StructMember3;
	}Struct_4118_t;

	typedef struct Struct_4142_t
	{
		struct Struct_4118_t 	StructMember0;
		long 	StructMember1;
	}Struct_4142_t;

	typedef struct Struct_4158_t
	{
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember0;
		[switch_is(StructMember0)] union union_3992 	StructMember1;
	}Struct_4158_t;

	typedef struct Struct_4178_t
	{
		long 	StructMember0;
		long 	StructMember1;
		struct Struct_126_t 	StructMember2;
	}Struct_4178_t;

	typedef struct Struct_4194_t
	{
		long 	StructMember0;
		long 	StructMember1;
		hyper 	StructMember2;
		hyper 	StructMember3;
		hyper 	StructMember4;
	}Struct_4194_t;

	typedef struct Struct_4208_t
	{
		[unique] [string] wchar_t* StructMember0;
		[unique] [string] wchar_t* StructMember1;
		long 	StructMember2;
		long 	StructMember3;
		[unique] [string] wchar_t* StructMember4;
		[unique] [string] wchar_t* StructMember5;
		[unique] [string] wchar_t* StructMember6;
		long 	StructMember7;
		struct Struct_126_t 	StructMember8;
		long 	StructMember9;
		long 	StructMember10;
		[unique] [string] wchar_t* StructMember11;
		long 	StructMember12;
		long 	StructMember13;
		long 	StructMember14;
		long 	StructMember15;
	}Struct_4208_t;

	typedef [switch_type(long)] union union_4280
	{
		[case(1)] [unique] struct Struct_4296_t* unionMember_1;
		/* no default member to print for this Union.
		An exception will be raised if the switch_is value does not match any of the cases values */
	} union_4280;


	typedef struct Struct_4296_t
	{
		long 	StructMember0;
		long 	StructMember1;
		long 	StructMember2;
		long 	StructMember3;
		hyper 	StructMember4;
		struct Struct_1516_t 	StructMember5;
		struct Struct_1516_t 	StructMember6;
	}Struct_4296_t;

	typedef struct Struct_4314_t
	{
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember0;
		[switch_is(StructMember0)] union union_4280 	StructMember1;
	}Struct_4314_t;

	typedef struct Struct_4334_t
	{
		long 	StructMember0;
		long 	StructMember1;
		struct Struct_126_t 	StructMember2;
		long 	StructMember3;
		long 	StructMember4;
		[unique] [string] wchar_t* StructMember5;
		[unique] [string] wchar_t* StructMember6;
		[unique] [string] wchar_t* StructMember7;
		[unique] [string] wchar_t* StructMember8;
		[unique] [string] wchar_t* StructMember9;
		[unique] [string] wchar_t* StructMember10;
		[unique] [string] wchar_t* StructMember11;
		[unique] [string] wchar_t* StructMember12;
		[unique] [string] wchar_t* StructMember13;
		[unique] [string] wchar_t* StructMember14;
		[unique] [string] wchar_t* StructMember15;
		[unique] [string] wchar_t* StructMember16;
		[unique] [string] wchar_t* StructMember17;
		[unique] [string] wchar_t* StructMember18;
		[unique] [string] wchar_t* StructMember19;
		[unique] [string] wchar_t* StructMember20;
		[unique] [string] wchar_t* StructMember21;
		[unique] [string] wchar_t* StructMember22;
		[unique] [string] wchar_t* StructMember23;
		[unique] [string] wchar_t* StructMember24;
		[unique] [string] wchar_t* StructMember25;
		[unique] [string] wchar_t* StructMember26;
		[unique] [string] wchar_t* StructMember27;
		[unique] [string] wchar_t* StructMember28;
		[unique] [string] wchar_t* StructMember29;
	}Struct_4334_t;

	typedef [switch_type(long)] union union_4494
	{
		[case(1)] [unique] struct Struct_4510_t* unionMember_1;
		/* no default member to print for this Union.
		An exception will be raised if the switch_is value does not match any of the cases values */
	} union_4494;


	typedef struct Struct_4510_t
	{
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember0;
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember1;
		hyper 	StructMember2;
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember3;
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember4;
		hyper 	StructMember5;
		[unique] wchar_t* StructMember6;
	}Struct_4510_t;

	typedef struct Struct_4530_t
	{
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember0;
		[switch_is(StructMember0)] union union_4494 	StructMember1;
	}Struct_4530_t;

	typedef [switch_type(long)] union union_4580
	{
		[case(1)] [unique] struct Struct_4620_t* unionMember_1;
		/* no default member to print for this Union.
		An exception will be raised if the switch_is value does not match any of the cases values */
	} union_4580;


	typedef struct Struct_4620_t
	{
		[unique] [size_is(StructMember1)] char* StructMember0;
		long 	StructMember1;
		[unique] [size_is(StructMember3)] char* StructMember2;
		long 	StructMember3;
		hyper 	StructMember4;
		long 	StructMember5;
		long 	StructMember6;
		long 	StructMember7;
		long 	StructMember8;
		long 	StructMember9;
	}Struct_4620_t;

	typedef struct Struct_4650_t
	{
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember0;
		[switch_is(StructMember0)] union union_4580 	StructMember1;
	}Struct_4650_t;

	typedef [switch_type(long)] union union_4688
	{
		[case(1)] [unique] struct Struct_4704_t* unionMember_1;
		/* no default member to print for this Union.
		An exception will be raised if the switch_is value does not match any of the cases values */
	} union_4688;


	typedef struct Struct_4704_t
	{
		[unique] [string] wchar_t* StructMember0;
		long 	StructMember1;
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember2;
		[unique] [string] wchar_t* StructMember3;
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember4;
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember5;
		[unique] [string] wchar_t* StructMember6;
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember7;
	}Struct_4704_t;

	typedef struct Struct_4734_t
	{
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember0;
		[switch_is(StructMember0)] union union_4688 	StructMember1;
	}Struct_4734_t;

	typedef struct Struct_4778_t
	{
		long 	StructMember0;
		[unique] [size_is(StructMember0)] char* StructMember1;
	}Struct_4778_t;

	typedef struct Struct_4838_t
	{
		long 	StructMember0;
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember1;
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember2;
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember3;
		long 	StructMember4;
		long 	StructMember5;
		[unique] /* [DBG] FC_BOGUS_ARRAY */ [size_is(StructMember4)] /*  */ struct Struct_4778_t** StructMember6;
		[unique] /* [DBG] FC_BOGUS_ARRAY */ [size_is(StructMember5)] /*  */ struct Struct_4778_t** StructMember7;
	}Struct_4838_t;

	typedef struct Struct_4886_t
	{
		long 	StructMember0;
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember1;
		long 	StructMember2;
		[unique] /* [DBG] FC_BOGUS_ARRAY */ [size_is(StructMember2)] /*  */ struct Struct_4838_t** StructMember3;
	}Struct_4886_t;

	typedef struct Struct_4918_t
	{
		/* enum_32 : typedef [v1_enum] enum  */ long 	StructMember0;
		struct Struct_16_t 	StructMember1;
		long 	StructMember2;
		char 	StructMember3[16];
		long 	StructMember4;
		char 	StructMember5;
		short 	StructMember6;
		short 	StructMember7;
		short 	StructMember8;
		short 	StructMember9;
	}Struct_4918_t;

	long Proc0_ServerMpEnableFeature(
		[in] /* enum_32 : typedef [v1_enum] enum  */ long arg_1,
		[in]long arg_2,
		[out]error_status_t* arg_3);

	long Proc1_ServerMpDisableFeature(
		[in] /* enum_32 : typedef [v1_enum] enum  */ long arg_1,
		[out]error_status_t* arg_2);

	long Proc2_ServerMpQueryStatus(
		[in] /* enum_32 : typedef [v1_enum] enum  */ long arg_1,
		[in]long arg_2,
		[out]struct Struct_144_t* arg_3,
		[out]error_status_t* arg_4);

	long Proc3_ServerMpEventOpen(
		[in] /* enum_32 : typedef [v1_enum] enum  */ long arg_1,
		[in]long arg_2,
		[in] /* enum_32 : typedef [v1_enum] enum  */ long arg_3,
		[in]long arg_4,
		[out]struct Struct_16_t* arg_5,
		[out][context_handle] void** arg_6,
		[out]error_status_t* arg_7);

	long Proc4_ServerMpEventClose(
		[in][out][context_handle] void** arg_1,
		[out]error_status_t* arg_2);

	long Proc5_ServerMpEventQueryNotification(
		[in][context_handle] void* arg_0,
		[out][ref]struct Struct_970_t** arg_1,
		[out]error_status_t* arg_2);

	long Proc6_ServerMpOnDemandStartScan(
		[in] /* enum_32 : typedef [v1_enum] enum  */ long arg_1,
		[in] /* enum_32 : typedef [v1_enum] enum  */ long arg_2,
		[in]long arg_3,
		[in]long arg_4,
		[in][unique] /* [DBG] FC_BOGUS_ARRAY */[size_is(arg_4)] /*  */ struct Struct_476_t* arg_5,
		[in]long arg_6,
		[out]struct Struct_16_t* arg_7,
		[out][context_handle] void** arg_8,
		[out]error_status_t* arg_9);

	long Proc7_ServerMpOnDemandQueryNotification(
		[in][context_handle] void* arg_0,
		[out][ref]struct Struct_970_t** arg_1,
		[out]error_status_t* arg_2);

	long Proc8_ServerMpOnDemandQueryScanResult(
		[in][context_handle] void* arg_0,
		[out]struct Struct_78_t* arg_1,
		[out]error_status_t* arg_2);

	long Proc9_ServerMpOnDemandControlScan(
		[in][context_handle] void* arg_0,
		[in] /* enum_32 : typedef [v1_enum] enum  */ long arg_1,
		[out]error_status_t* arg_2);

	long Proc10_ServerMpOnDemandControlSystemScan(
		[in] /* enum_32 : typedef [v1_enum] enum  */ long arg_1,
		[out]error_status_t* arg_2);

	long Proc11_ServerMpOnDemandPersistScan(
		[in][context_handle] void* arg_0,
		[in]long arg_1,
		[out]error_status_t* arg_2);

	long Proc12_ServerMpOnDemandCloseScan(
		[in][out][context_handle] void** arg_1,
		[out]error_status_t* arg_2);

	long Proc13_ServerMpOnDemandThreatOpen(
		[in][context_handle] void* arg_0,
		[out][context_handle] void** arg_1,
		[out]error_status_t* arg_2);

	long Proc14_ServerMpOnDemandThreatEnum(
		[in][context_handle] void* arg_0,
		[out][ref]struct Struct_1232_t** arg_1,
		[out]error_status_t* arg_2);

	long Proc15_ServerMpOnDemandThreatClose(
		[in][context_handle] void* arg_0,
		[in][out][context_handle] void** arg_1,
		[out]error_status_t* arg_2);

	long Proc16_ServerMpScanOpenThreatHistory(
		[in] /* enum_32 : typedef [v1_enum] enum  */ long arg_1,
		[in] /* enum_32 : typedef [v1_enum] enum  */ long arg_2,
		[out][context_handle] void** arg_3,
		[out]error_status_t* arg_4);

	long Proc17_ServerMpScanEnumerateThreatHistory(
		[in][context_handle] void* arg_0,
		[out][ref]struct Struct_1232_t** arg_1,
		[out]error_status_t* arg_2);

	long Proc18_ServerMpScanEnumerateDetectionHistory(
		[in][context_handle] void* arg_0,
		[out][ref]struct Struct_1382_t** arg_1,
		[out]error_status_t* arg_2);

	long Proc19_ServerMpScanCloseThreatHistory(
		[in][out][context_handle] void** arg_1,
		[out]error_status_t* arg_2);

	long Proc20_ServerMpScanDeleteThreatHistory(
		[in] /* enum_32 : typedef [v1_enum] enum  */ long arg_1,
		[out]error_status_t* arg_2);

	long Proc21_ServerMpRpcCleanOpen(
		[in] /* enum_32 : typedef [v1_enum] enum  */ long arg_1,
		[in][unique]struct Struct_1434_t* arg_2,
		[in]long arg_3,
		[out][context_handle] void** arg_4,
		[out]error_status_t* arg_5);

	long Proc22_ServerMpRpcScanCleanOpen(
		[in][context_handle] void* arg_0,
		[in][unique]struct Struct_1434_t* arg_1,
		[out][context_handle] void** arg_2,
		[out]error_status_t* arg_3);

	long Proc23_ServerMpRpcCleanStart(
		[in][context_handle] void* arg_0,
		[in]long arg_1,
		[out]struct Struct_16_t* arg_2,
		[out]error_status_t* arg_3);

	long Proc24_ServerMpRpcCleanControl(
		[in][context_handle] void* arg_0,
		[in] /* enum_32 : typedef [v1_enum] enum  */ long arg_1,
		[out]error_status_t* arg_2);

	long Proc25_ServerMpRpcCleanThreatsNotification(
		[in][context_handle] void* arg_0,
		[out][ref]struct Struct_970_t** arg_1,
		[out]error_status_t* arg_2);

	long Proc26_ServerMpRpcPrecheckStart(
		[in][context_handle] void* arg_0,
		[in]long arg_1,
		[out]struct Struct_16_t* arg_2,
		[out]error_status_t* arg_3);

	long Proc27_ServerMpRpcPrecheckNotification(
		[in][context_handle] void* arg_0,
		[out][ref]struct Struct_970_t** arg_1,
		[out]error_status_t* arg_2);

	long Proc28_ServerMpRpcCleanQuery(
		[in][context_handle] void* arg_0,
		[out]struct Struct_16_t* arg_1,
		[out]error_status_t* arg_2);

	long Proc29_ServerMpRpcCleanClose(
		[in][out][context_handle] void** arg_1,
		[out]error_status_t* arg_2);

	long Proc30_MpService__CMpMapsLatencyDataIterator__Clone(
		[in]long arg_1,
		[in]long arg_2,
		[in]long arg_3,
		[out]error_status_t* arg_4);

	long Proc31_MpService__CMpMapsLatencyDataIterator__Clone(
		[in]long arg_1,
		[in]long arg_2,
		[in]long arg_3,
		[in]long arg_4,
		[out]error_status_t* arg_5);

	long Proc32_MpService__CMpMapsLatencyDataIterator__Clone(
		[in]long arg_1,
		[in]hyper arg_2,
		[in]long arg_3,
		[in]long arg_4,
		[out]error_status_t* arg_5);

	long Proc33_MpService__CMpMapsLatencyDataIterator__Clone(
		[in]long arg_1,
		[in][string] wchar_t* arg_2,
		[in]long arg_3,
		[out]error_status_t* arg_4);

	long Proc34_ServerMpQuarantineEnumOpen(
		[in] /* enum_32 : typedef [v1_enum] enum  */ long arg_1,
		[out][context_handle] void** arg_2,
		[out]error_status_t* arg_3);

	long Proc35_ServerMpQuarantineEnumerate(
		[in][context_handle] void* arg_0,
		[out]struct Struct_16_t* arg_1,
		[out]error_status_t* arg_2);

	long Proc36_ServerMpQuarantineEnumClose(
		[in][out][context_handle] void** arg_1,
		[out]error_status_t* arg_2);

	long Proc37_ServerMpQuarantineQueryInfo(
		[in] /* enum_32 : typedef [v1_enum] enum  */ long arg_1,
		[in]struct Struct_16_t* arg_2,
		[out][ref]struct Struct_1232_t** arg_3,
		[out]error_status_t* arg_4);

	long Proc38_ServerMpQuarantineRestoreThreat(
		[in] /* enum_32 : typedef [v1_enum] enum  */ long arg_1,
		[in]long arg_2,
		[in]struct Struct_16_t* arg_3,
		[in][string] wchar_t* arg_4,
		[out]error_status_t* arg_5);

	long Proc39_ServerMpQuarantineDeleteThreat(
		[in] /* enum_32 : typedef [v1_enum] enum  */ long arg_1,
		[in]struct Struct_16_t* arg_2,
		[out]error_status_t* arg_3);

	long Proc40_ServerMpStateEnumOpen(
		[out][context_handle] void** arg_1,
		[out]error_status_t* arg_2);

	long Proc41_ServerMpQueryEngineVersion(
		[out]struct Struct_1536_t* arg_1,
		[out]error_status_t* arg_2);

	long Proc42_ServerMpUpdateEngineSignature(
		[in] /* enum_32 : typedef [v1_enum] enum  */ long arg_1,
		[in][string] wchar_t* arg_2,
		[out]error_status_t* arg_3);

	long Proc43_ServerMpRollbackEngineSignature(
		[in] /* enum_32 : typedef [v1_enum] enum  */ long arg_1,
		[in] /* enum_32 : typedef [v1_enum] enum  */ long arg_2,
		[out]error_status_t* arg_3);

	long Proc44_ServerMpThreatStaticInfo(
		[in] /* enum_32 : typedef [v1_enum] enum  */ long arg_1,
		[in]hyper arg_2,
		[out][ref]struct Struct_1232_t** arg_3,
		[out]error_status_t* arg_4);

	long Proc45_ServerMpQuerySystemInfo(
		[in]struct Struct_16_t* arg_1,
		[in]long arg_2,
		[in][size_is(arg_2)]char* arg_3,
		[out]long* arg_4,
		[out][ref][size_is(, *arg_4)]char** arg_5,
		[out]error_status_t* arg_6);

	long Proc46_ServerMpRpcConfigSetValue(
		[in][string] wchar_t* arg_1,
		[in][string] wchar_t* arg_2,
		[in]long arg_3,
		[in]long arg_4,
		[in][size_is(arg_4)]char* arg_5,
		[out]error_status_t* arg_6);

	long Proc47_ServerMpRpcConfigDelValue(
		[in][string] wchar_t* arg_1,
		[in][string] wchar_t* arg_2,
		[out]error_status_t* arg_3);

	long Proc48_ServerMpRpcElevationHandleOpen(
		[out]struct Struct_16_t* arg_1,
		[out][context_handle] void** arg_2,
		[out]error_status_t* arg_3);

	long Proc49_ServerMpRpcElevationHandleAttach(
		[in]struct Struct_16_t* arg_1,
		[out][context_handle] void** arg_2,
		[out]error_status_t* arg_3);

	long Proc50_ServerMpRpcElevationHandleClose(
		[in]long arg_1,
		[in][out][context_handle] void** arg_2,
		[out]error_status_t* arg_3);

	long Proc51_ServerMpRpcElevateCleanHandle(
		[in][context_handle] void* arg_0,
		[in][context_handle] void* arg_1,
		[out]error_status_t* arg_2);

	long Proc52_ServerMpRpcSignatureThreatOpen(
		[in] /* enum_32 : typedef [v1_enum] enum  */ long arg_1,
		[in]long arg_2,
		[out][context_handle] void** arg_3,
		[out]error_status_t* arg_4);

	long Proc53_ServerMpRpcSignatureThreatEnum(
		[in][context_handle] void* arg_0,
		[in]long arg_1,
		[out][ref]struct Struct_1232_t** arg_2,
		[out]error_status_t* arg_3);

	long Proc54_ServerMpRpcSignatureThreatClose(
		[in][out][context_handle] void** arg_1,
		[out]error_status_t* arg_2);

	long Proc55_ServerMpRpcGetSampleInfo(
		[in]long arg_1,
		[in]struct Struct_16_t* arg_2,
		[out][ref]struct Struct_1740_t** arg_3,
		[out]error_status_t* arg_4);

	long Proc56_ServerMpRpcQueryScansWithSamples(
		[in]long arg_1,
		[out]long* arg_2,
		[out][ref] /* [DBG] FC_BOGUS_ARRAY */[size_is(, *arg_2)] /*  */ struct Struct_16_t** arg_3,
		[out]error_status_t* arg_4);

	long Proc57_ServerMpRpcDropScansWithSamples(
		[in]long arg_1,
		[in]long arg_2,
		[in] /* [DBG] FC_BOGUS_ARRAY */[size_is(arg_2)] /*  */ struct Struct_16_t* arg_3,
		[out]error_status_t* arg_4);

	long Proc58_ServerMpRpcSpynetQueueCreate(
		[in]struct Struct_16_t* arg_1,
		[in]long arg_2,
		[out]struct Struct_16_t* arg_3,
		[out][context_handle] void** arg_4,
		[out]error_status_t* arg_5);

	long Proc59_ServerMpRpcSpynetQueueQueryNotification(
		[in][context_handle] void* arg_0,
		[out][context_handle] void** arg_1,
		[out]long* arg_2,
		[out]error_status_t* arg_3);

	long Proc60_ServerMpRpcSpynetQueueClose(
		[in][out][context_handle] void** arg_1,
		[out]error_status_t* arg_2);

	long Proc61_ServerMpRpcSpynetGenerateReport(
		[in][context_handle] void* arg_0,
		[out]long* arg_1,
		[out][ref][size_is(, *arg_1)]char** arg_2,
		[out]long* arg_3,
		[out]struct Struct_110_t* arg_4,
		[out]struct Struct_16_t* arg_5,
		[out]error_status_t* arg_6);

	long Proc62_ServerMpRpcSenseGenerateReport(
		[in][context_handle] void* arg_0,
		[out]long* arg_1,
		[out][ref][size_is(, *arg_1)]char** arg_2,
		[out]error_status_t* arg_3);

	long Proc63_ServerMpRpcSpynetOnResponse(
		[in][context_handle] void* arg_0,
		[in]struct Struct_1872_t* arg_1,
		[in]long arg_2,
		[in][unique][size_is(arg_2)]char* arg_3,
		[in] /* enum_32 : typedef [v1_enum] enum  */ long arg_4,
		[out]long* arg_5,
		[out][ref][size_is(, *arg_5)]char** arg_6,
		[out]error_status_t* arg_7);

	long Proc64_ServerMpRpcSpynetGetStartTime(
		[in][context_handle] void* arg_0,
		[out]struct Struct_28_t* arg_1,
		[out]error_status_t* arg_2);

	long Proc65_ServerMpRpcSpynetUpdateSpynetMetrics(
		[in][context_handle] void* arg_0,
		[in]struct Struct_1920_t* arg_1,
		[in]long arg_2,
		[out]error_status_t* arg_3);

	long Proc66_ServerMpRpcSpynetClose(
		[in][out][context_handle] void** arg_1,
		[out]error_status_t* arg_2);

	long Proc67_ServerMpRpcSigUpdServiceOpen(
		[out]struct Struct_16_t* arg_1,
		[out][context_handle] void** arg_2,
		[out]error_status_t* arg_3);

	long Proc68_ServerMpRpcSigUpdServiceQueryNotification(
		[in][context_handle] void* arg_0,
		[out][ref]struct Struct_1978_t** arg_1,
		[out]error_status_t* arg_2);

	long Proc69_ServerMpRpcSigUpdServiceSendProgressNotification(
		[in][context_handle] void* arg_0,
		[in]struct Struct_970_t* arg_1,
		[out]error_status_t* arg_2);

	long Proc70_ServerMpRpcSigUpdServiceClose(
		[in][out][context_handle] void** arg_1,
		[out]error_status_t* arg_2);

	long Proc71_ServerMpRpcSigUpdClientOpen(
		[in]long arg_1,
		[out]struct Struct_16_t* arg_2,
		[out][context_handle] void** arg_3,
		[out]error_status_t* arg_4);

	long Proc72_ServerMpRpcSigUpdClientQueryNotification(
		[in][context_handle] void* arg_0,
		[out][ref]struct Struct_970_t** arg_1,
		[out]error_status_t* arg_2);

	long Proc73_ServerMpRpcSigUpdClientClose(
		[in][out][context_handle] void** arg_1,
		[out]error_status_t* arg_2);

	long Proc74_ServerMpRpcSigUpdControl(
		[in]struct Struct_1978_t* arg_1,
		[out]error_status_t* arg_2);

	long Proc75_ServerMpRpcIdleNotificationOpen(
		[in][string] wchar_t* arg_1,
		[out][context_handle] void** arg_2,
		[out]error_status_t* arg_3);

	long Proc76_ServerMpRpcIdleNotificationClose(
		[in][out][context_handle] void** arg_1,
		[out]error_status_t* arg_2);

	long Proc77_ServerMpRpcNotifyIdle(
		[in][context_handle] void* arg_0,
		[in]long arg_1,
		[out]error_status_t* arg_2);

	long Proc78_ServerMpRpcIdleCheckTaskCompletion(
		[in][context_handle] void* arg_0,
		[out]error_status_t* arg_1);

	long Proc79_ServerMpRpcThreatOpen(
		[in] /* enum_32 : typedef [v1_enum] enum  */ long arg_1,
		[in] /* enum_32 : typedef [v1_enum] enum  */ long arg_2,
		[in]long arg_3,
		[out][context_handle] void** arg_4,
		[out]error_status_t* arg_5);

	long Proc80_ServerMpRpcThreatEnumerate(
		[in][context_handle] void* arg_0,
		[out][ref]struct Struct_1232_t** arg_1,
		[out]error_status_t* arg_2);

	long Proc81_ServerMpRpcThreatClose(
		[in][out][context_handle] void** arg_1,
		[out]error_status_t* arg_2);

	long Proc82_ServerMpRpcDbgThreatViewAction(
		[in]long arg_1,
		[out]error_status_t* arg_2);

	long Proc83_ServerMpRpcForcedReboot(
		[in]long arg_1,
		[out]error_status_t* arg_2);

	long Proc84_MpService__CMpMapsLatencyDataIterator__Clone(
		[out]error_status_t* arg_1);

	long Proc85_ServerMpRpcAddFastPathSignatureFile(
		[in][string] wchar_t* arg_1,
		[out][ref]struct Struct_2070_t** arg_2,
		[in]long arg_3,
		[out]error_status_t* arg_4);

	long Proc86_ServerMpRpcRemoveFastPathSignatureFile(
		[in][string] wchar_t* arg_1,
		[in]long arg_2,
		[out]error_status_t* arg_3);

	long Proc87_ServerMpRpcDynamicSignatureOpen(
		[in]long arg_1,
		[out][context_handle] void** arg_2,
		[out]error_status_t* arg_3);

	long Proc88_ServerMpRpcDynamicSignatureEnumerate(
		[in][context_handle] void* arg_0,
		[out][ref]struct Struct_2070_t** arg_1,
		[out]error_status_t* arg_2);

	long Proc89_ServerMpRpcDynamicSignatureClose(
		[in][out][context_handle] void** arg_1,
		[out]error_status_t* arg_2);

	long Proc90_MpService__CMpMapsLatencyDataIterator__Clone(
		[out]struct Struct_16_t* arg_1,
		[out][context_handle] void** arg_2,
		[out]error_status_t* arg_3);

	long Proc91_MpService__CMpMapsLatencyDataIterator__Clone(
		[in][context_handle] void* arg_0,
		[out][ref]struct Struct_970_t** arg_1,
		[out]error_status_t* arg_2);

	long Proc92_MpService__CMpMapsLatencyDataIterator__Clone(
		[in][context_handle] void* arg_0,
		[out]error_status_t* arg_1);

	long Proc93_MpService__CMpMapsLatencyDataIterator__Clone(
		[in][out][context_handle] void** arg_1,
		[out]error_status_t* arg_2);

	long Proc94_ServerMpRpcMemoryScanStart(
		[in]struct Struct_126_t* arg_1,
		[in]long arg_2,
		[in]struct Struct_2516_t* arg_3,
		[out]struct Struct_16_t* arg_4,
		[out][context_handle] void** arg_5,
		[out]error_status_t* arg_6);

	long Proc95_ServerMpRpcMemoryScanQueryNotification(
		[in][context_handle] void* arg_0,
		[out][ref]struct Struct_970_t** arg_1,
		[out]error_status_t* arg_2);

	long Proc96_ServerMpRpcMemoryScanClose(
		[in][out][context_handle] void** arg_1,
		[out]error_status_t* arg_2);

	long Proc97_ServerMpRpcFastMemoryScanOpen(
		[in]struct Struct_126_t* arg_1,
		[out]struct Struct_2558_t* arg_2,
		[out][context_handle] void** arg_3,
		[out]error_status_t* arg_4);

	long Proc98_ServerMpRpcFastMemoryScan(
		[in][context_handle] void* arg_0,
		[in]long arg_1,
		[in]struct Struct_2442_t* arg_2,
		[out]struct Struct_110_t* arg_3,
		[out]error_status_t* arg_4);

	long Proc99_ServerMpRpcFastMemoryScanClose(
		[in][out][context_handle] void** arg_0,
		[out]error_status_t* arg_1);

	long Proc100_ServerMpRpcFastMemoryScanCacheInfo(
		[out]struct Struct_2558_t* arg_1,
		[out]error_status_t* arg_2);

	long Proc101_ServerMpRpcAmsiCloseSession(
		[in]hyper arg_1,
		[out]error_status_t* arg_2);

	long Proc102_ServerMpRpcTcgLogScan(
		[in]long arg_1,
		[in][unique][size_is(arg_1)]char* arg_2,
		[out]long* arg_3,
		[out]long* arg_4,
		[out][ref][size_is(, *arg_4)]char** arg_5,
		[out]error_status_t* arg_6);

	long Proc103_ServerMpRpcTcgLogApplyExtResult(
		[in]long arg_1,
		[in][unique][size_is(arg_1)]char* arg_2,
		[out]error_status_t* arg_3);

	long Proc104_ServerMpRpcDbgSendCallbackNotification(
		[in] /* enum_32 : typedef [v1_enum] enum  */ long arg_1,
		[in]struct Struct_970_t* arg_2,
		[out]error_status_t* arg_3);

	long Proc105_ServerMpRpcThreatRollup(
		[in]long arg_1,
		[in]long arg_2,
		[out][ref]struct Struct_2640_t** arg_3,
		[out]error_status_t* arg_4);

	long Proc106_ServerMpDetectionQuery(
		[in][context_handle] void* arg_0,
		[in]struct Struct_16_t* arg_1,
		[out][ref]struct Struct_1232_t** arg_2,
		[out]error_status_t* arg_3);

	long Proc107_ServerMpRpcRequestSnooze(
		[in]long arg_1,
		[out]error_status_t* arg_2);

	long Proc108_ServerMpRpcOfflineScanInstall(
		[out]error_status_t* arg_1);

	long Proc109_ServerMpRpcOfflineScanStatusQuery(
		[out]struct Struct_2680_t* arg_1,
		[out]error_status_t* arg_2);

	long Proc110_ServerMpRpcTriggerHeartbeatOnDefenderDisable(
		[in][string] wchar_t* arg_1,
		[out]error_status_t* arg_2);

	long Proc111_ServerMpRpcTriggerHeartbeatOnUninstall(
		[out]error_status_t* arg_1);

	long Proc112_ServerMpRpcTriggerErrorHeartbeatReport(
		[in] /* enum_32 : typedef [v1_enum] enum  */ long arg_1,
		[in][string] wchar_t* arg_2,
		[in][string] wchar_t* arg_3,
		[in][string] wchar_t* arg_4,
		[out]error_status_t* arg_5);

	long Proc113_ServerMpRpcTriggerHeartbeatReport(
		[out][ref]struct Struct_1872_t** arg_1,
		[out]error_status_t* arg_2);

	long Proc114_ServerMpRpcRemapCallistoDetections(
		[in][string] wchar_t* arg_1,
		[in]long arg_2,
		[in][size_is(arg_2)]wchar_t* arg_3,
		[out]error_status_t* arg_4);

	long Proc115_ServerMpRpcGetCallistoDetections(
		[out]long* arg_1,
		[out][ref] /* [DBG] FC_BOGUS_ARRAY */[size_is(, *arg_1)] /*  */ struct Struct_1232_t*** arg_2,
		[out]error_status_t* arg_3);

	long Proc116_ServerMpRpcIsAdlFallbackDue(
		[in][string] wchar_t* arg_1,
		[out]long* arg_2,
		[out]error_status_t* arg_3);

	long Proc117_ServerMpRpcIsRtpAutoEnable(
		[out]long* arg_1,
		[out]long* arg_2,
		[out]long* arg_3,
		[out]error_status_t* arg_4);

	long Proc118_ServerMpRpcEngineQueryConfigDword(
		[in][string] wchar_t* arg_1,
		[out]long* arg_2,
		[out]error_status_t* arg_3);

	long Proc119_ServerMpRpcSampleHeaderQueueCreate(
		[in]struct Struct_16_t* arg_1,
		[in]long arg_2,
		[out]struct Struct_16_t* arg_3,
		[out][context_handle] void** arg_4,
		[out]error_status_t* arg_5);

	long Proc120_ServerMpRpcSampleHeaderQueueQueryNotification(
		[in][context_handle] void* arg_0,
		[out][context_handle] void** arg_1,
		[out]long* arg_2,
		[out]error_status_t* arg_3);

	long Proc121_ServerMpRpcSampleHeaderQueueClose(
		[in][out][context_handle] void** arg_1,
		[out]error_status_t* arg_2);

	long Proc122_ServerMpRpcSampleHeaderClose(
		[in][out][context_handle] void** arg_1,
		[out]error_status_t* arg_2);

	long Proc123_ServerMpRpcSampleHeaderGetSampleDetails(
		[in][context_handle] void* arg_0,
		[out][ref]struct Struct_2798_t** arg_1,
		[out]error_status_t* arg_2);

	long Proc124_ServerMpRpcGetSampleChunk(
		[in][string] wchar_t* arg_1,
		[out]long* arg_2,
		[out][ref][size_is(, *arg_2)]char** arg_3,
		[out]error_status_t* arg_4);

	long Proc125_ServerMpRpcConveySampleSubmissionResult(
		[in]struct Struct_2854_t* arg_1,
		[out]error_status_t* arg_2);

	long Proc126_ServerMpRpcGetSampleListRequiringConsent(
		[out]long* arg_1,
		[out][ref] /* [DBG] FC_BOGUS_ARRAY */[size_is(, *arg_1)] /*  */ struct Struct_2900_t*** arg_2,
		[out]error_status_t* arg_3);

	long Proc127_ServerMpRpcConveyUserChoiceForSampleList(
		[in]long arg_1,
		[in][unique] /* [DBG] FC_BOGUS_ARRAY */[size_is(arg_1)] /*  */ struct Struct_2900_t** arg_2,
		[out]error_status_t* arg_3);

	long Proc128_ServerMpRpcGetRunningMode(
		[out] /* enum_32 : typedef [v1_enum] enum  */ long* arg_1,
		[out]error_status_t* arg_2);

	long Proc129_ServerMpRpcIsGivenRunningModeSupported(
		[in] /* enum_32 : typedef [v1_enum] enum  */ long arg_1,
		[out]long* arg_2,
		[out]error_status_t* arg_3);

	long Proc130_ServerMpDisableXBGM(
		[out]error_status_t* arg_1);

	long Proc131_ServerMpDisableXBGM(
		[out]error_status_t* arg_1);

	long Proc132_ServerMpXBGMUpdateIV(
		[in]hyper arg_1,
		[in]char* arg_2,
		[in]hyper arg_3,
		[out]error_status_t* arg_4);

	long Proc133_ServerDlpMpRpcDlpIsPrintDetoursNeeded(
		[out][ref]struct Struct_3040_t** arg_1,
		[out]error_status_t* arg_2);

	long Proc134_ServerDlpMpRpcDlpIsPrintDetoursNeeded(
		[in]struct Struct_3040_t* arg_1,
		[out]error_status_t* arg_2);

	long Proc135_ServerMpOnDemandStartScan2(
		[in] /* enum_32 : typedef [v1_enum] enum  */ long arg_1,
		[in] /* enum_32 : typedef [v1_enum] enum  */ long arg_2,
		[in]long arg_3,
		[in]long arg_4,
		[in][unique] /* [DBG] FC_BOGUS_ARRAY */[size_is(arg_4)] /*  */ struct Struct_476_t* arg_5,
		[in]long arg_6,
		[in] /* enum_32 : typedef [v1_enum] enum  */ long arg_7,
		[out]struct Struct_16_t* arg_8,
		[out][context_handle] void** arg_9,
		[out]error_status_t* arg_10);

	long Proc136_ServerMpQueryDefaultFolderGuardList(
		[out]long* arg_1,
		[out][ref] /* [DBG] FC_BOGUS_ARRAY */[size_is(, *arg_1)] /*  */ struct Struct_16_t** arg_2,
		[out]error_status_t* arg_3);

	long Proc137_ServerMpRpcTriggerStatusRefreshNotification(
		[out]error_status_t* arg_1);

	long Proc138_ServerMpRpcGetHIPSRuleInfo(
		[out]long* arg_1,
		[out][ref] /* [DBG] FC_BOGUS_ARRAY */[size_is(, *arg_1)] /*  */ struct Struct_3108_t*** arg_2,
		[out]error_status_t* arg_3);

	long Proc139_ServerMpEnableSmartLocker(
		[out]error_status_t* arg_1);

	long Proc140_ServerMpDisableSmartLocker(
		[out]error_status_t* arg_1);

	long Proc141_ServerMpXBGMUpdateIV(
		[in]long arg_1,
		[in][size_is(arg_1)]char* arg_2,
		[in]hyper arg_3,
		[out]error_status_t* arg_4);

	long Proc142_ServerMpFlushLowfiCache(
		[out]error_status_t* arg_1);

	long Proc143_ServerMpRpcGetAsrBlockedProcesses(
		[in]struct Struct_16_t* arg_1,
		[in]long arg_2,
		[out]long* arg_3,
		[out][ref] /* [DBG] FC_BOGUS_ARRAY */[size_is(, *arg_3)] /*  */ struct Struct_3166_t*** arg_4,
		[out]error_status_t* arg_5);

	long Proc144_ServerMpRpcGetAsrBlockedActions(
		[in]struct Struct_16_t* arg_1,
		[in] /* enum_32 : typedef [v1_enum] enum  */ long arg_2,
		[in]long arg_3,
		[out]long* arg_4,
		[out][ref] /* [DBG] FC_BOGUS_ARRAY */[size_is(, *arg_4)] /*  */ struct Struct_3220_t*** arg_5,
		[out]error_status_t* arg_6);

	long Proc145_ServerMpRpcDeleteAsrHistory(
		[out]error_status_t* arg_1);

	long Proc146_ServerMpGetTaskSchedulerStrings(
		[out][ref]struct Struct_3280_t** arg_1,
		[out]error_status_t* arg_2);

	long Proc147_ServerMpRpcGetAsrBlockedActionInfos(
		[in]struct Struct_16_t* arg_1,
		[in] /* enum_32 : typedef [v1_enum] enum  */ long arg_2,
		[in]long arg_3,
		[out]long* arg_4,
		[out][ref] /* [DBG] FC_BOGUS_ARRAY */[size_is(, *arg_4)] /*  */ struct Struct_3302_t*** arg_5,
		[out]error_status_t* arg_6);

	long Proc148_ServerMpRpcGetTPStateInfo(
		[out]struct Struct_3350_t* arg_1,
		[out]error_status_t* arg_2);

	long Proc149_ServerMpRpcSetTPState(
		[in] /* enum_32 : typedef [v1_enum] enum  */ long arg_1,
		[out]error_status_t* arg_2);

	long Proc150_ServerMpRpcUpdateDevMode(
		[out]long* arg_1,
		[out]error_status_t* arg_2);

	long Proc151_ServerMpRpcGetDevMode(
		[out]long* arg_1,
		[out]error_status_t* arg_2);

	long Proc152_ServerMpUpdateBreakTheGlassStatus(
		[in]long arg_1,
		[in][string] wchar_t* arg_2,
		[in][string] wchar_t* arg_3,
		[out]error_status_t* arg_4);

	long Proc153_ServerMpNetworkCapture(
		[in][string] wchar_t* arg_1,
		[out]error_status_t* arg_2);

	long Proc154_ServerMpConveyDlpBypass(
		[in]long arg_1,
		[in][unique][string] wchar_t* arg_2,
		[in][unique][string] wchar_t* arg_3,
		[in][unique][string] wchar_t* arg_4,
		[out]error_status_t* arg_5);

	long Proc155_ServerDlpMpCheckAccessForPrintOperation(
		[in]long arg_1,
		[in]hyper arg_2,
		[in][unique][string] wchar_t* arg_3,
		[in][unique][string] wchar_t* arg_4,
		[in][unique][string] wchar_t* arg_5,
		[in]long arg_6,
		[out]long* arg_7,
		[out]error_status_t* arg_8);

	long Proc156_ServerDlpMpConveyNewPrinterConnection(
		[in][unique][string] wchar_t* arg_1,
		[in][unique][string] wchar_t* arg_2,
		[in][unique][string] wchar_t* arg_3,
		[in]long arg_4,
		[out]error_status_t* arg_5);

	long Proc157_ServerMpShowDlpDetailsDialog(
		[in][unique][string] wchar_t* arg_1,
		[in]long arg_2,
		[in][unique][string] wchar_t* arg_3,
		[in]long arg_4,
		[out]error_status_t* arg_5);

	long Proc158_ServerMpRpcGetDlpEvents(
		[in]long arg_1,
		[out]long* arg_2,
		[out][ref] /* [DBG] FC_BOGUS_ARRAY */[size_is(, *arg_2)] /*  */ struct Struct_3370_t*** arg_3,
		[out]error_status_t* arg_4);

	long Proc159_ServerMpRpcConveyUserChoiceForDlpNotification(
		[in]long arg_1,
		[in][unique] /* [DBG] FC_BOGUS_ARRAY */[size_is(arg_1)] /*  */ struct Struct_3370_t** arg_2,
		[in][unique][string] wchar_t* arg_3,
		[in]long arg_4,
		[in][unique][string] wchar_t* arg_5,
		[in]long arg_6,
		[out]error_status_t* arg_7);

	long Proc160_ServerMpRpcChangeCapability(
		[in] /* enum_32 : typedef [v1_enum] enum  */ long arg_1,
		[in]long arg_2,
		[in]long arg_3,
		[out]error_status_t* arg_4);

	long Proc161_ServerMpRpcMpThreatAction(
		[in] /* enum_32 : typedef [v1_enum] enum  */ long arg_1,
		[in]struct Struct_3570_t* arg_2,
		[in] /* enum_32 : typedef [v1_enum] enum  */ long arg_3,
		[out]error_status_t* arg_4);

	long Proc162_ServerMpRpcAsrSetHipsUserExclusion(
		[in]long arg_1,
		[in]struct Struct_16_t* arg_2,
		[in]long arg_3,
		[in]long arg_4,
		[in]long arg_5,
		[in][unique][string] wchar_t* arg_6,
		[in][unique][string] wchar_t* arg_7,
		[in][unique][string] wchar_t* arg_8,
		[in][unique][string] wchar_t* arg_9,
		[out]error_status_t* arg_10);

	long Proc163_ServerDlpMpRpcCheckAccessForClipboardOperationEx(
		[in]long arg_1,
		[in]hyper arg_2,
		[in]long arg_3,
		[out]long* arg_4,
		[out]long* arg_5,
		[out]long* arg_6,
		[out]error_status_t* arg_7);

	long Proc164_ServerMpRpcQueryConfigProtection(
		[in][string] wchar_t* arg_1,
		[in][string] wchar_t* arg_2,
		[in]long arg_3,
		[out]long* arg_4,
		[out]error_status_t* arg_5);

	long Proc165_ServerMpRpcCheckAccessForDragDropOperation(
		[in]long arg_1,
		[in]hyper arg_2,
		[in]long arg_3,
		[in]long arg_4,
		[in]hyper arg_5,
		[in]long arg_6,
		[in][unique][size_is(arg_6)]char* arg_7,
		[out]long* arg_8,
		[out]error_status_t* arg_9);

	long Proc166_ServerMpRpcUpdateBrowserActiveTab(
		[in][string] wchar_t* arg_1,
		[in]long arg_2,
		[in]long arg_3,
		[in][string] wchar_t* arg_4,
		[in]long arg_5,
		[out]error_status_t* arg_6);

	long Proc167_ServerMpRpcSendBrowserHeartbeat(
		[in][string] wchar_t* arg_1,
		[in]long arg_2,
		[in]hyper arg_3,
		[in]long arg_4,
		[out]hyper* arg_5,
		[out]error_status_t* arg_6);

	long Proc168_ServerMpRpcGetThreatExecutionInfo(
		[in]hyper arg_1,
		[in]long arg_2,
		[out][ref]struct Struct_3654_t** arg_3,
		[out]error_status_t* arg_4);

	long Proc169_ServerMpRpcReportClipboardOwner(
		[in]long arg_1,
		[in]hyper arg_2,
		[in]long arg_3,
		[out]error_status_t* arg_4);

	long Proc170_ServerMpRpcDlpDelegateEnforcement(
		[in]long arg_1,
		[out]error_status_t* arg_2);

	long Proc171_ServerMpRpcConveyUserChoiceForDlpNotificationEx(
		[in]long arg_1,
		[in][unique] /* [DBG] FC_BOGUS_ARRAY */[size_is(arg_3)] /*  */ struct Struct_3370_t** arg_2,
		[in]long arg_3,
		[in][unique][string] wchar_t* arg_4,
		[in]long arg_5,
		[in][unique][string] wchar_t* arg_6,
		[in]long arg_7,
		[out]error_status_t* arg_8);

	long Proc172_ServerMpRpcSendDeviceControlToast(
		[in]long arg_1,
		[in][unique][string] wchar_t* arg_2,
		[in][unique][string] wchar_t* arg_3,
		[in][unique][string] wchar_t* arg_4,
		[out]error_status_t* arg_5);

	long Proc173_ServerMpRpcIsDeviceControlAvailable(
		[out]long* arg_1,
		[out]error_status_t* arg_2);

	long Proc174_ServerMpRpcGetFCValue(
		[in]hyper arg_1,
		[out]long* arg_2,
		[out]error_status_t* arg_3);

	long Proc175_ServerMpRpcSetDriverUnloadInProgress(
		[in]char arg_1,
		[out]error_status_t* arg_2);

	long Proc176_ServerMpRpcUpdateTSMode(
		[in][string] wchar_t* arg_1,
		[out]error_status_t* arg_2);

	long Proc177_ServerMpRpcGetTSModeInfo(
		[in] /* enum_32 : typedef [v1_enum] enum  */ long arg_1,
		[out][ref]struct Struct_3800_t** arg_2,
		[out]error_status_t* arg_3);

	long Proc178_ServerMpCheckAccessForPrintOperation2(
		[in]long arg_1,
		[in]hyper arg_2,
		[in][unique][string] wchar_t* arg_3,
		[in][unique][string] wchar_t* arg_4,
		[in][unique][string] wchar_t* arg_5,
		[in]long arg_6,
		[in][out][unique]long* arg_7,
		[out]long* arg_8,
		[out]error_status_t* arg_9);

	long Proc179_ServerMpRpcCheckAccessForClipboardOperationEx2(
		[in]long arg_1,
		[in]hyper arg_2,
		[in][unique]struct Struct_3824_t* arg_3,
		[in][unique]struct Struct_3824_t* arg_4,
		[in]long arg_5,
		[out]long* arg_6,
		[out]long* arg_7,
		[out]long* arg_8,
		[out]error_status_t* arg_9);

	long Proc180_ServerMpRpcCheckAccessForDragDropOperation2(
		[in]long arg_1,
		[in]hyper arg_2,
		[in]long arg_3,
		[in]long arg_4,
		[in]hyper arg_5,
		[in]long arg_6,
		[in][unique][size_is(arg_6)]char* arg_7,
		[in][unique]struct Struct_3824_t* arg_8,
		[in][unique]struct Struct_3824_t* arg_9,
		[out]long* arg_10,
		[out]error_status_t* arg_11);

	long Proc181_ServerMpRpcDlpInitializeEnforcementMode(
		[in]long arg_1,
		[in][unique] /* [DBG] FC_BOGUS_ARRAY */[size_is(arg_1)] /*  */ struct Struct_126_t* arg_2,
		[out]error_status_t* arg_3);

	long Proc182_ServerMpRpcDlpGetOperationEnforcmentMode(
		[in]long arg_1,
		[out]long* arg_2,
		[out]error_status_t* arg_3);

	long Proc183_ServerMpRpcDlpNotifyPreOpenDocumentFile(
		[in]struct Struct_3824_t* arg_1,
		[out]error_status_t* arg_2);

	long Proc184_ServerMpRpcDlpNotifyPostOpenDocumentFile(
		[in]struct Struct_3824_t* arg_1,
		[in][unique]struct Struct_126_t* arg_2,
		[out]error_status_t* arg_3);

	long Proc185_ServerMpRpcDlpNotifyCloseDocumentFile(
		[in][unique]struct Struct_3824_t* arg_1,
		[out]error_status_t* arg_2);

	long Proc186_ServerMpRpcDlpNotifyPreSaveAsDocument(
		[in]struct Struct_3824_t* arg_1,
		[in][unique][string] wchar_t* arg_2,
		[out]error_status_t* arg_3);

	long Proc187_ServerMpRpcDlpNotifyPostSaveAsDocument(
		[in]struct Struct_3824_t* arg_1,
		[in][unique][string] wchar_t* arg_2,
		[in][unique]struct Struct_126_t* arg_3,
		[out]error_status_t* arg_4);

	long Proc188_ServerMpRpcDlpNotifyPrePrint(
		[in]struct Struct_3824_t* arg_1,
		[in][unique]struct Struct_3880_t* arg_2,
		[out]error_status_t* arg_3);

	long Proc189_ServerMpRpcDlpNotifyPostStartPrint(
		[in][unique]struct Struct_3824_t* arg_1,
		[in][unique]struct Struct_3880_t* arg_2,
		[in][unique]struct Struct_126_t* arg_3,
		[out]error_status_t* arg_4);

	long Proc190_ServerMpGetTDTFeatureStatus(
		[out]long* arg_1,
		[out]error_status_t* arg_2);

	long Proc191_ServerMpRpcGetDeviceControlSecurityPolicies(
		[out][ref][string] wchar_t** arg_1,
		[out][ref][string] wchar_t** arg_2,
		[out]error_status_t* arg_3);

	long Proc192_ServerMpRpcGetSACInfo(
		[in] /* enum_32 : typedef [v1_enum] enum  */ long arg_1,
		[out][ref]struct Struct_3958_t** arg_2,
		[out]error_status_t* arg_3);

	long Proc193_ServerMpGetTDTFeatureStatusEx(
		[in] /* enum_32 : typedef [v1_enum] enum  */ long arg_1,
		[out][ref]struct Struct_4158_t** arg_2,
		[out]error_status_t* arg_3);

	long Proc194_ServerMpRpcGetDeviceControlStatus(
		[out]struct Struct_4178_t* arg_1,
		[out]error_status_t* arg_2);

	long Proc195_ServerMpRpcSpynetGetExtendedHeaderInfo(
		[in][context_handle] void* arg_0,
		[out]struct Struct_4194_t* arg_1,
		[out]error_status_t* arg_2);

	long Proc196_ServerMpDisableXBGM(
		[out]error_status_t* arg_1);

	long Proc197_ServerMpRpcDefenderPrintAccessCheck(
		[in]long arg_1,
		[in][string] wchar_t* arg_2,
		[out]long* arg_3,
		[out]hyper* arg_4,
		[out]long* arg_5,
		[out]error_status_t* arg_6);

	long Proc198_ServerMpRpcDeviceControlPrintAccessCheck(
		[in]long arg_1,
		[in][string] wchar_t* arg_2,
		[out]long* arg_3,
		[out]hyper* arg_4,
		[out]long* arg_5,
		[out]error_status_t* arg_6);

	long Proc199_ServerMpRpcDefenderPrintDataProvide(
		[in]hyper arg_1,
		[in]long arg_2,
		[in][unique][size_is(arg_2)]char* arg_3,
		[out]error_status_t* arg_4);

	long Proc200_ServerMpRpcDeviceControlAuthenticateNetworkShare(
		[in][string] wchar_t* arg_1,
		[in]long arg_2,
		[in][unique][size_is(arg_2)]char* arg_3,
		[out]error_status_t* arg_4);

	long Proc201_ServerMpRpcApplyTrustLabelAceForMDE(
		[in][string] wchar_t* arg_1,
		[in]long arg_2,
		[out]error_status_t* arg_3);

	long Proc202_ServerMpGetNpSupportFile(
		[out][ref][string] wchar_t** arg_1,
		[out]error_status_t* arg_2);

	long Proc203_ServerDlpMpRpcDlpIsPrintDetoursNeeded(
		[out]long* arg_1,
		[out]error_status_t* arg_2);

	long Proc204_ServerMpRpcConfigRefresh(
		[in][string] wchar_t* arg_1,
		[out]error_status_t* arg_2);

	long Proc205_ServerMpServiceLogMessage(
		[in][string] wchar_t* arg_1,
		[out]error_status_t* arg_2);

	long Proc206_ServerMpRpcDeviceControlValidateDataDuplicationRemoteLocationConfiguration(
		[in][string] wchar_t* arg_1,
		[out][ref][string] wchar_t** arg_2,
		[out]error_status_t* arg_3);

	long Proc207_ServerMpRpcDlpGetEvidenceFileUrl(
		[in]long arg_1,
		[in][string] wchar_t* arg_2,
		[in]long arg_3,
		[in][unique][string] wchar_t* arg_4,
		[in][unique][string] wchar_t* arg_5,
		[out][ref][string] wchar_t** arg_6,
		[out][ref][string] wchar_t** arg_7,
		[out]error_status_t* arg_8);

	long Proc208_ServerMpRpcDlpCheckAccessForBuffer(
		[in]long arg_1,
		[in][size_is(arg_1)]char* arg_2,
		[in]long arg_3,
		[in][unique][string] wchar_t* arg_4,
		[out]long* arg_5,
		[out][ref][size_is(, *arg_5)]char** arg_6,
		[out][ref][string] wchar_t** arg_7,
		[out][ref][string] wchar_t** arg_8,
		[out]error_status_t* arg_9);

	long Proc209_ServerMpRpcDevVolumesProtectionState(
		[out] /* enum_32 : typedef [v1_enum] enum  */ long* arg_1,
		[out]error_status_t* arg_2);

	long Proc210_ServerMpRpcQueryDevVolumeProtectionState(
		[in][string] wchar_t* arg_1,
		[out] /* enum_32 : typedef [v1_enum] enum  */ long* arg_2,
		[out]error_status_t* arg_3);

	long Proc211_ServerMpRpcDlpDispatchAccessEvent(
		[in]struct Struct_4208_t* arg_1,
		[out]error_status_t* arg_2);

	long Proc212_ServerMpRpcCheckAccessForCopyFile(
		[in]long arg_1,
		[in]long arg_2,
		[in]long arg_3,
		[in]hyper arg_4,
		[in][string] wchar_t* arg_5,
		[in][string] wchar_t* arg_6,
		[in][string] wchar_t* arg_7,
		[out]long* arg_8,
		[out]error_status_t* arg_9);

	long Proc213_ServerMpRpcAsrSetHipsUserExclusionEx(
		[in][string] wchar_t* arg_1,
		[out]error_status_t* arg_2);

	long Proc214_ServerMpRpcGetUpToDateInfo(
		[in] /* enum_32 : typedef [v1_enum] enum  */ long arg_1,
		[out][ref]struct Struct_4314_t** arg_2,
		[out]error_status_t* arg_3);

	long Proc215_ServerMpRpcSendDlpEventDataToEngine(
		[in]struct Struct_4334_t* arg_1,
		[out]error_status_t* arg_2);

	long Proc216_ServerMpRpcAccessibilityAsyncEvent(
		[in]long arg_1,
		[in]long arg_2,
		[in]hyper arg_3,
		[in][string] wchar_t* arg_4,
		[out]error_status_t* arg_5);

	long Proc217_ServerMpRpcCacheManagerIsTrusted(
		[in]long arg_1,
		[in]hyper arg_2,
		[in]hyper arg_3,
		[out]error_status_t* arg_4);

	long Proc218_ServerMpRpcSCCGetState(
		[in] /* enum_32 : typedef [v1_enum] enum  */ long arg_1,
		[out][ref]struct Struct_4530_t** arg_2,
		[out]error_status_t* arg_3);

	long Proc219_ServerMpRpcSCCReset(
		[out]error_status_t* arg_1);

	long Proc220_ServerMpRpcImportConfigPayload(
		[in][size_is(arg_2)]char* arg_1,
		[in]long arg_2,
		[in] /* enum_32 : typedef [v1_enum] enum  */ long arg_3,
		[out][ref]struct Struct_4650_t** arg_4,
		[out]error_status_t* arg_5);

	long Proc221_ServerMpRpcGetConfigPayloadStatus(
		[in] /* enum_32 : typedef [v1_enum] enum  */ long arg_1,
		[in] /* enum_32 : typedef [v1_enum] enum  */ long arg_2,
		[out][ref]struct Struct_4650_t** arg_3,
		[out]error_status_t* arg_4);

	long Proc222_ServerMpRpcGetConfigValue(
		[in]wchar_t* arg_1,
		[in] /* enum_32 : typedef [v1_enum] enum  */ long arg_2,
		[in] /* enum_32 : typedef [v1_enum] enum  */ long arg_3,
		[out][ref]struct Struct_4734_t** arg_4,
		[out]error_status_t* arg_5);

	long Proc223_ServerMpRpcEffectiveConfigurationReport(
		[in][string] wchar_t* arg_1,
		[out][ref][size_is(, *arg_3)]char** arg_2,
		[out]long* arg_3,
		[out]error_status_t* arg_4);

	long Proc224_ServerMpRpcGetDefenderStatusSummary(
		[out]long* arg_1,
		[out]error_status_t* arg_2);

	long Proc225_ServerMpRpcGetHIPSCustomRuleInfo(
		[out]long* arg_1,
		[out][ref] /* [DBG] FC_BOGUS_ARRAY */[size_is(, *arg_1)] /*  */ struct Struct_3108_t*** arg_2,
		[out]error_status_t* arg_3);

	long Proc226_ServerMpRpcGetTrustAnchors(
		[in][unique][string] wchar_t* arg_1,
		[in]long arg_2,
		[out][ref]struct Struct_4886_t** arg_3,
		[out]error_status_t* arg_4);

	long Proc227_ServerMpRpcDlpTriggerToast(
		[in][string] wchar_t* arg_1,
		[out]error_status_t* arg_2);

	long Proc228_ServerMpRpcGetRnBWFPFilters(
		[out]long* arg_1,
		[out][ref] /* [DBG] FC_BOGUS_ARRAY */[size_is(, *arg_1)] /*  */ struct Struct_4918_t*** arg_2,
		[out]error_status_t* arg_3);

	long Proc229_ServerMpRpcRemoveRnBWFPFilter(
		[in]struct Struct_16_t* arg_1,
		[out]error_status_t* arg_2);

	long Proc230_ServerMpRpcSenseTriggerToast(
		[in]long arg_1,
		[out]error_status_t* arg_2);

	long Proc231_ServerMpRpcWddControl(
		[in]long arg_1,
		[in][unique][size_is(arg_3)]char* arg_2,
		[in]long arg_3,
		[out][ref][size_is(, *arg_5)]char** arg_4,
		[out]long* arg_5,
		[out]error_status_t* arg_6);

	long Proc232_ServerMpRpcTemporaryExclusionAction(
		[in]long arg_1,
		[in][string] wchar_t* arg_2,
		[out]error_status_t* arg_3);

	long Proc233_ServerMpOnDemandCancelScan(
		[in][context_handle] void* arg_0,
		[in] /* enum_32 : typedef [v1_enum] enum  */ long arg_1,
		[out]error_status_t* arg_2);

	long Proc234_ServerMpRpcSCCForceReset(
		[in][size_is(arg_2)]char* arg_1,
		[in]long arg_2,
		[out]error_status_t* arg_3);

	long Proc235_ServerMpRpcPublishModularConfig(
		[in][string] wchar_t* arg_1,
		[in][string] wchar_t* arg_2,
		[in]long arg_3,
		[out]error_status_t* arg_4);
}